### PR TITLE
fix!(supabase_flutter, gotrue): Load session from local storage first, and lazily refresh session later.

### PR DESCRIPTION
**Pull request by dshukertjr**
## What kind of change does this PR introduce?

This PR updates the SDK to not hang at `Supabase.initialize()` for token refresh. Instead, it will fetch the session from local storage, and use it as the initial session. 

## New Supabase initialization flow:
1. `Supabase.initialize()` is called
2. session from local storage is obtained
3. gotrue sets the session obtained from local storage as `_currentSession` (even if it had expired) and emits `initialSession` event
4. `auth.recoverSession()` is called, but not awaited, so `Supabase.initialize()` is completed without waiting for network requests

Also in step 4 if `recoverSession()` fails and throws an `AuthException`, such as when the session string was malformed, or the user didn't enable auto refresh token and the access token had expired, gotrue calls `signOut()`, which will trigger the local storage to be deleted by `SupabaseAuth` class. Calling `signOut()` has benefits of triggering `signedOut` event on `onAuthStateChanged`, which is nice, because before this update, the user's session was silently deleted from local storage, and there were no feedback to the developer about the user getting kicked out. 

## Things to note:
- Before this update, `_currentSession` was guaranteed to be fresh right after `Supabase.initialize()` was completed, but that is no longer the case. 
  - There could be a case where the local storage session seemed valid, but the auth server rejected, hence the user gets signed out right away, which feels like the desired behavior, but it is a change from the current one.

## Other

fixes https://github.com/supabase/supabase-flutter/issues/668
fixes https://github.com/supabase/supabase-flutter/issues/630
fixes https://github.com/supabase/supabase-flutter/issues/716
related https://github.com/supabase/supabase-flutter/issues/662

### CODE REVIEW

**Review by Vinzent03 — APPROVED** [review]

**Comment by tom-at-pixel** [comment]
Does supabase-js have the same behavior as this PR introduces? In other words, does `supabase.auth.initialize()` instantly consume the cached token and then in the background refreshes the token via network? This would be particularly useful on the client (especially for mobile apps). 😊

**Comment by dshukertjr** [comment]
@tom-at-pixel 
JS SDK works in a slightly different way, but creating a Supabase client does not block initializing the app either, so it's good to be used in mobile apps as well!

**Comment by tom-at-pixel** [comment]
@dshukertjr The main problem in the JS SDK is that if there's no internet on app boot, the cached token is not only ignored but also removed, leaving the user in a singed out state. I recognize this is another issue entirely, so I can look for or create a new issue as needed. Thanks for the info!

**Comment by dshukertjr** [comment]
@tom-at-pixel 
Oh, I see. If that is the case, that might be unintended behavior, so if you could open an issue on the gotrue-js repo, that would be awesome!
https://github.com/supabase/gotrue-js

**Pull request merged**
