### PR TITLE
Rework the implementation

### PR DESCRIPTION
**Pull request by bdlukaa**
## What kind of change does this PR introduce?

Rework the singleton

## What is the current behavior?

To initialize it:

```dart
import 'package:supabase_flutter/supabase_flutter.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  Supabase(
    url: SUPABASE_URL,
    anonKey: SUPABASE_ANNON_KEY,
    authCallbackUrlHostname: 'login-callback', // optional
    debug: true // optional
  );

  runApp(MyApp());
}
```

To access the supabase instance:

```dart
import 'package:supabase_flutter/supabase_flutter.dart';

final response = await Supabase().client.auth.signIn(email: _email, password: _password);
```

## What is the new behavior?

To initialize it:
```dart
import 'package:supabase_flutter/supabase_flutter.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  Supabase.initialize(
    url: SUPABASE_URL,
    anonKey: SUPABASE_ANNON_KEY,
    authCallbackUrlHostname: 'login-callback', // optional
    debug: true // optional
  );

  runApp(MyApp());
}
```

To access the supabase instance:

```dart
import 'package:supabase_flutter/supabase_flutter.dart';

final response = await Supabase.instance.client.auth.signIn(email: _email, password: _password);
```

## Additional context

This rework comes with the purpose of making the library more dev-friendly. The documentation of some methods were also updated

### CODE REVIEW

**Comment by phamhieu** [comment]
Wow, that's fast. Great work! @bdlukaa. Thank you

Can you fix the 2 lint errors. I will merge the PR after that.

**Comment by bdlukaa** [comment]
@phamhieu done! Please test it before merging

**Comment by phamhieu** [comment]
@bdlukaa can you fix the unit test

Screenshot 2021-07-19 at 6 57 14 AM

**Comment by bdlukaa** [comment]
@phamhieu Done! All tests passing locally for me

> ✓ can access Supabase singleton
> ✓ can parse deeplink
> ✓ can parse flutter web redirect link
> ✓ can parse flutter web custom page redirect link

**Pull request merged**
