### PR TITLE
Expose a deeplinks stream controller to allow non-supabase related deeplinks handling

### PR DESCRIPTION
**Pull request by romaingyh**
## What kind of change does this PR introduce?

This PR adds a `Stream<Uri>`  to `SupabaseAuth.dart`, it allows to listen for deeplinks not handled by supabase auth.

## What is the current behavior?

Currently we can't listen for deeplinks using plugins like `AppLinks` because `supabase_flutter` also uses it for auth (email validation, password reset...) and after experimentations, when there are two (or more) subscriptions to `AppLinks`'s uri stream, only one (the last or first registered I don't remember exactly) can receive events.

I think it's the cause of #541 and this PR should solve it.

## What is the new behavior?

The added Stream property make a bridge between `AppLinks` and user's app. We can use 
```dart
SupabaseAuth.instance.uriLinksStream.listen((event) {
    debugPrint('New uri link: $event');
});
```
in ours apps to listen for deeplinks _not handled by supabase_.

## Additional context

I'm not sure if `SupabaseAuth.dart` is the good place to add this code, I hesitated with SupabaseClient or GoTrueClient, let me know.
Also with this implementation, only the links not handled by supabase are added to the the Stream.

### CODE REVIEW

**Comment by Vinzent03** [comment]
On which platform did you have that issue? As said [here](https://github.com/supabase/supabase-flutter/issues/541), I couldn't reproduce that issue.

**Comment by romaingyh** [comment]
> On which platform did you have that issue? As said [here](https://github.com/supabase/supabase-flutter/issues/541), I couldn't reproduce that issue. And make sure it's after `runApp` so best to use the api from App Links at the same place where you would listen to the supabase exposed api in your code.

Hello, sorry for late reply. Here is a code to reproduce the issue. Now I can confirm only the last added listener to `Applinks` will receive events.

```dart
import 'package:app_links/app_links.dart';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Supabase.initialize(
    url: const String.fromEnvironment('SUPABASE_URL'),
    anonKey: const String.fromEnvironment('SUPABASE_ANON_KEY'),
    authCallbackUrlHostname: 'auth',
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Deep links PR'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('Last deeplink opened :'),
            StreamBuilder(
              stream: AppLinks().allUriLinkStream,
              builder: (context, uri) {
                return Text(
                  '${uri.data}',
                  style: Theme.of(context).textTheme.headlineMedium,
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
Running on ios simulator with `flutter run --dart-define-from-file=.env.json`. I created a fresh supabase project for this test, url and supabase key are in `.env.json` file. I set pr.deeplinks://auth as redirect url in dashboard and also configured the corresponding scheme/host in Info.plist and AndroidManifest.

If you run code like this and open :
`pr.deeplinks://auth`
`pr.deeplinks://other`

Both will works and will be displayed on screen, they've been handled by the stream listener but not Supabase.

You can comment lines 49 to 57 to remove listener, restart app and now re-open `pr.deeplinks://auth`. There is an error in console that confirms Supabase was not handling the deeplink before with the StreamBuilder.

I can provide my repo if you can't reproduce

**Comment by Vinzent03** [comment]
I'm pretty sure I already tested this on android and/or linux device and couldn't reproduce. But I wouldn't wonder if that's an Apple only issue. I don't have a mac device, so can @dshukertjr verify this? 

Instead of fixing this in supabase-flutter, I would instead fix that in `app_links` so that they create only one stream and broadcast that.

**Review by gadfly361 — APPROVED** [review]

**Comment by gadfly361** [comment]
My apologies, didn't mean to approve, accidental click.

**Comment by dshukertjr** [comment]
Closing in favor of https://github.com/supabase/supabase-flutter/pull/848

**Comment by proformance** [comment]
I am also struggling with this; I cannot use AppLink in my app for other uses due to supabase-flutter already reading the stream. I initially came up with a very similar solution before I noticed this PR and https://github.com/supabase/supabase-flutter/issues/541.

I don't think #848 solves the issue, reason being that disabling it only allows me to use one or the other.


I do however I fully agree with 

> ...
> Instead of fixing this in supabase-flutter, I would instead fix that in `app_links` so that they create only one stream and broadcast that.

I tried to solve it here, seems to work for me now, let's hope it gets merged
https://github.com/llfbandit/app_links/pull/145

**Comment by proformance** [comment]
It's now available in [6.2.0](https://pub.dev/packages/app_links/changelog) 🎉

**Pull request closed without merging**
