### PR TITLE
chore(release): publish packages

### PR DESCRIPTION
**Pull request by dshukertjr**
- realtime_client@1.3.0
 - supabase@1.11.7
 - supabase_flutter@1.10.20
 
(Hopefully) the last release for v1 🚀

### CODE REVIEW

**Comment by Vinzent03** [comment]
I've merged now #653 as well into main, so this should be integrated into the changelog.

**Comment by dshukertjr** [comment]
I think the easiest would be to just do two releases right now. Would that be fine? I will create another release right after merging this one.

**Comment by Vinzent03** [comment]
Because of the tags right? The branch management should be easy, but you would have to remove the tags. I'm not really familiar with how that's handled, so if that's easier for you, do two releases.

**Comment by dshukertjr** [comment]
@Vinzent03 Yeah, let's just do two releases. Do you want to approve this PR?

**Comment by Vinzent03** [comment]
But creating another release with the #653  being in history before this is merged might also create issues. I actually think it's easier to try to remove this release.

**Review by Vinzent03 — APPROVED** [review]

**Comment by dshukertjr** [comment]
@Vinzent03 It's alright, I would just publish it from `chore/publish` branch.

**Pull request merged**
