### PR TITLE
feat: Add support for formatted json

### PR DESCRIPTION
**Pull request by devsdocs**
## What kind of change does this PR introduce?

Feature

## What is the current behavior?

Currently does not support output in formatted json.

## What is the new behavior?

Ouput is also available in formatted json.

## Additional context

None

### CODE REVIEW

**Comment by dshukertjr** [comment]
Just trying to understand the use case here. Why do you need this feature?

**Comment by devsdocs** [comment]
For debugging purposes, it is easy to look at.

**Comment by Vinzent03** [comment]
@devsdocs Are you using the `yet_another_json_isolate` as a standalone package or through some supabase packages?

**Comment by Vinzent03** [comment]
Closing because of no response. Just comment if you still believe this should be added, and I'm open to reopen this pr.

**Pull request closed without merging**
