### PR TITLE
chore: publish v2.0.0-dev.0

### PR DESCRIPTION
**Pull request by dshukertjr**
Also includes a small change to `melos.yaml` to copy the proper version number long with `dev` suffix to each `version.dart` file.

### CODE REVIEW

**Comment by Vinzent03** [comment]
I think the postgrest builder and supabase package config changes should be documented. So how to migrate to v2.

**Comment by dshukertjr** [comment]
@Vinzent03 Yeah, there are a lot of documentations to be done. I will have them by the time this comes out of developer preview.

**Comment by Vinzent03** [comment]
The reason behind a dev version is that some people can already try and test the new version. But without documentation on how to migrate, less people will take that effort.
I think at least the new count and config API should be easy visible in the changelog.
I also think it's standard to do that migration guide for dev version as well.

**Comment by dshukertjr** [comment]
@Vinzent03 This v2 is a relatively minor upgrade from v1. Most of the APIs are the same, and those that have changed have changed in an intuitive way with enough comment documentation. Early adaptors that want to try out v2 developer preview should be fine with it. This developer preview still has possibilities of changing, so I will document the final result.

**Review by Vinzent03 — APPROVED** [review]

**Pull request merged**
