### PR TITLE
chore: one time manual package release

### PR DESCRIPTION
**Pull request by dshukertjr**
## What kind of change does this PR introduce?

[Melos](https://melos.invertase.dev/) has made a lot of the process easy and simple, but it seems like [we have to do one last manual release](https://melos.invertase.dev/guides/automated-releases#not-using-conventional-commits). 

After merging this PR and releasing all the packages and archiving all the sub packages, we will work on a PR to setup fully automated release process here https://github.com/supabase/supabase-flutter/pull/463.

### CODE REVIEW

**Comment by dshukertjr** [comment]
It seems like we need to bump the minimum Dart version to 2.17.0 to fix the issue with CI.

> WARNING: Dart 2.17.0 or greater is required to use Melos with pubspec overrides.
>   - functions_client
>     └> packages/functions_client
>        └> Failed to install.

We can do this in another PR, and might be a good one to test out the automated release process once that is done.

**Comment by Vinzent03** [comment]
What exactly is the reason for this release? Just to be able to only have conventional commits for the next automatic release?

Regarding the dart version. I think we should(?) allow Dart 3.0.

**Comment by dshukertjr** [comment]
@Vinzent03 
I guess the biggest reason for this update is to update the link on pub.dev. 

Screenshot 2023-05-12 at 0 35 38

For updating the Dart versions, we can properly open a fix PR to update them.

**Review by Vinzent03 — APPROVED** [review]
Ah I've missed the repository url update.

**Review by bdlukaa — APPROVED** [review]

**Pull request merged**
